### ISSUE TITLE
Writing documentation 

### ISSUE THREAD

**Issue by anguyen216** [amjacob2/reimplementation-back-end#5]

**Comment by jdjohns4** [comment]
for reference:

* wiki is here: https://expertiza.csc.ncsu.edu/index.php/CSC/ECE_517_Spring_2023_-_E2311._Reimplement_QuizQuestion_and_its_child_classes
* intro/test demonstration video is here: https://drive.google.com/file/d/1WWgir8u_10FblUVBFtBPd7RRgiJVqbOA/view
* future work api demo instance here: http://152.7.178.122:3000/api/v1/quiz_questions/show?type=MultipleChoiceCheckbox
